# Generated by Django 5.0.6 on 2024-09-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(blank=True, max_length=255)),
                ("Phone", models.CharField(blank=True, max_length=255)),
                ("Email", models.CharField(blank=True, max_length=255)),
                ("Subject", models.CharField(blank=True, max_length=255)),
                ("Message", models.TextField(blank=True)),
                ("method", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="chatbot",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("AuthEmail", models.CharField(max_length=255)),
                ("Role", models.CharField(default="owner", max_length=20)),
                ("createAT", models.DateTimeField(blank=True)),
                ("LastMessageAT", models.DateTimeField(blank=True, null=True)),
                ("chats", models.IntegerField(default=0)),
                ("messages", models.IntegerField(default=0)),
                (
                    "AuthID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Auth.auth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(blank=True, max_length=255)),
                (
                    "chatbotID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chatbot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatbotDesign",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("ChatbotName", models.CharField(max_length=255)),
                (
                    "Avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("WelcomeMessage", models.TextField(blank=True, null=True)),
                ("UnableRelevantResponse", models.TextField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "monday_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("monday_end", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tuesday_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tuesday_end",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wed_start", models.CharField(blank=True, max_length=255, null=True)),
                ("wed_end", models.CharField(blank=True, max_length=255, null=True)),
                ("thur_start", models.CharField(blank=True, max_length=255, null=True)),
                ("thur_end", models.CharField(blank=True, max_length=255, null=True)),
                ("fri_start", models.CharField(blank=True, max_length=255, null=True)),
                ("fri_end", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "chatbotID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chatbot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatbotFileURL",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("FilePath", models.CharField(max_length=233)),
                (
                    "chatbotDesignID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.chatbotdesign",
                    ),
                ),
                (
                    "chatbotID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chatbot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message_body", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanAssistant",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chatID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chat"
                    ),
                ),
                (
                    "chatbotID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chatbot"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="form",
            name="HumanAssistantID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.humanassistant"
            ),
        ),
        migrations.CreateModel(
            name="QA",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("QAL", models.JSONField()),
                (
                    "chatID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplyEmail",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("reply_body", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "EmailID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("message_body", models.TextField()),
                ("message_sid", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplySMS",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=15)),
                ("reply_body", models.TextField()),
                ("message_sid", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "SMSID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sms"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteFileURL",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("WebURL", models.JSONField(max_length=233)),
                (
                    "chatbotDesignID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.chatbotdesign",
                    ),
                ),
                (
                    "chatbotID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.chatbot"
                    ),
                ),
            ],
        ),
    ]
