# Generated by Django 5.0.6 on 2024-09-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=50)),
                ("Password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ActivationCode",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("ActivationCode", models.CharField(max_length=11)),
                (
                    "AuthID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Auth.auth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("BusinessName", models.CharField(max_length=255)),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Auth.auth"
                    ),
                ),
            ],
        ),
    ]
